chore: mk post update script cleaner

diff --git a/run_after_update-all.sh.tmpl b/run_after_update-all.sh.tmpl
--- a/run_after_update-all.sh.tmpl
+++ b/run_after_update-all.sh.tmpl
@@ -1,86 +1,107 @@
 #!/usr/bin/env zsh
 
-# gum may not be avaialable on first run
+GUM_AVAILABLE=false
 if command -v gum >/dev/null 2>&1; then
-  gum log --time datetime --level info "Update Home : start"
-else 
-  echo "############ UPDATING ############"
+  GUM_AVAILABLE=true
 fi
 
-# update nix channels
+# Log depending on whether gum is available or not
+# if available, log first arg and use the otthers as structured data, 
+# otherwise just print the first arg
+function _info() {
+  if $GUM_AVAILABLE; then
+    gum log --time stampmilli --level info --structured $@
+  else
+    echo $1
+  fi
+}
+
+function _error() {
+  if $GUM_AVAILABLE; then
+    gum log --time stampmilli --level error --structured $@
+  else
+    echo "ERROR: $1" >&2
+  fi
+}
+
+# Run a taskl with reporting
+# first arg is the task name, the rest is the command to run
+function _task() {
+  if $GUM_AVAILABLE; then
+    _info "$1 : start"
+    gum spin --show-output --show-error --show-stderr --title "$1..." -- ${@:2}
+    _info "$1 : done"
+  else
+    echo "$1 : start"
+    ${@:2}
+    echo "$1 : done"
+  fi
+}
+
+# Ask for confirmation, return true if confirmed, false otherwise
+# Default to false, with a timeout of 5 seconds
+# First arg is the question
+function _confirm() {
+  if $GUM_AVAILABLE; then
+    return $(gum confirm "$1" --default=no --timeout=5s)
+  else
+    read -q -t 5 "CONFIRMATION?$1 [y/N] " 
+    if [[ $CONFIRMATION =~ ^[Yy]$ ]]; then 
+      return 0
+    else
+      return 1
+    fi
+  fi
+}
+
+_info "Running post-update script"
+
+_info "Checking env ..."
+
+NIX_AVAILABLE=false
 if command -v nix >/dev/null 2>&1; then
-  if command -v gum >/dev/null 2>&1; then
-    gum log --time datetime --level info "Update Nix channels : start"
-    gum spin --show-output --title "Updating..." -- nix-channel --update
-  else
-    echo "############ NIX ############"  
-    nix-channel --update
-  fi
-  if command -v gum >/dev/null 2>&1; then
-    if [ $? -eq 0 ]; then
-      gum log --time datetime --level info "Update Nix channels : done"
-    else
-      gum log --time datetime --level error "Update Nix channels : failed"
-    fi
-  fi
+  NIX_AVAILABLE=true
 fi
 
-# build and switch to the new home-manager configuration
+HOME_MANAGER_AVAILABLE=false
 if command -v home-manager >/dev/null 2>&1; then
-  if command -v gum >/dev/null 2>&1; then
-    gum log --time datetime --level info "Build new home derivation : start"
-  else
-    echo "############ HOME ############"
-  fi
-  gum spin --show-output --title "Building..." -- $HOME/.nix-profile/bin/home-manager switch -b backup
-  if command -v gum >/dev/null 2>&1; then
-    if [ $? -eq 0 ]; then
-      gum log --time datetime --level info "Build new home derivation : done"
-    else
-      gum log --time datetime --level error "Build new home derivation : failed"
-    fi
-  fi
+  HOME_MANAGER_AVAILABLE=true
+fi
+
+_info "Updating Home ..." \
+  nix $NIX_AVAILABLE \
+  home_manager $HOME_MANAGER_AVAILABLE \
+
+if $NIX_AVAILABLE; then
+  _task "Update Nix channels" nix-channel --update
+fi
+
+if $HOME_MANAGER_AVAILABLE; then
+  _task "Switch Home Manager derivation" $HOME/.nix-profile/bin/home-manager switch -b backup
 fi
 
 # sometimes completions need to be cleaned up
-if command -v gum >/dev/null 2>&1; then
-  gum log --time datetime --level info "Clean up completions : start"
-  gum spin --show-output --title "Cleaning..." -- find -L $HOME/.local/share/zinit/completions -type l -exec rm -- {} +
-  if [ $? -eq 0 ]; then
-    gum log --time datetime --level info "Clean up completions : done"
-  else
-    gum log --time datetime --level error "Clean up completions : failed"
-  fi
-else 
-  find -L $HOME/.local/share/zinit/completions -type l -exec rm -- {} +
-fi
+_task "Clean up completions" find -L $HOME/.local/share/zinit/completions -type l -exec rm -- {} +  
 
 # source zshrc
-if command -v gum >/dev/null 2>&1; then
-  gum log --time datetime --level info "Reload zshrc : start"
-fi
+_info "Reload .zshrc : start"
 source $HOME/.zshrc
-if command -v gum >/dev/null 2>&1; then
-  if [ $? -eq 0 ]; then
-    gum log --time datetime --level info "Reload zshrc : done"
-  else
-    gum log --time datetime --level error "Reload zshrc : failed"
-  fi
+_info "Reload .zshrc : done"
+
+ZINIT_AVAILABLE=false
+if (( ${+functions[zinit]} )); then
+  ZINIT_AVAILABLE=true
 fi
 
 # optionally update zinit plugins
 # this may take some toime hence why it's deactivated by default 
-if (( ${+functions[zinit]} )); then
-  if command -v gum >/dev/null 2>&1; then
-    if gum confirm "Update zinit plugins ? [y/N]" --default=no; then 
-      zinit update --all -p 8
-    fi
+if $ZINIT_AVAILABLE; then
+  if _confirm "Update zinit plugins ? [y/N]"; then 
+    zinit update --all -p 8
   fi
+else 
+  _error "Zinit not available, skipping plugin update"
 fi
 
-if command -v gum >/dev/null 2>&1; then
-  gum log --time datetime --level info "Update Home : done"
-else 
-  echo "############ DONE ############"
-fi
+_info "Running post-update script : done"
 
